name: Build

on:
  push

jobs:
  build-amd64:
    name: Build for x86 (64-bit)
    runs-on: ubuntu-latest
    steps:
      - name: Setup toolchain
        uses: ada-actions/toolchain@ce2021
        with:
          distrib: fsf
          target: native
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build from source
        run: make datadir=/usr/local/share/words commands sorter
        shell: bash
      - name: Upload binary snapshots
        uses: actions/upload-artifact@v2
        with:
          name: binaries_amd64
          path: bin

  build-arm32:
    name: Build for ARM (32-bit)
    runs-on: ubuntu-latest
    steps:
      - name: Setup toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gprbuild gnat gnat-9-arm-linux-gnueabi
        shell: bash
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build from source
        run: |
          gprconfig --target=arm-linux-gnueabi && \
          make \
          datadir="/usr/local/share/words" \
          GPRBUILD_OPTIONS="-j4 --target=arm-linux-gnueabi" \
          ADAFLAGS="-Wl,-pie" \
          commands sorter && \
          file bin/words
        shell: bash
      - name: Upload binary snapshots
        uses: actions/upload-artifact@v2
        with:
          name: binaries_arm
          path: bin

